### PR TITLE
added warden deploy manifest

### PR DESCRIPTION
**Pull request by gramos**
I added a warden deploy example file

### CODE REVIEW

**Comment by gramos** [comment]
Hi, I work for Altoros. The company has already signed the agreement. In fact, during February and March I was pairing at Pivotal offices

**Comment by hiremaga** [comment]
Publicizing your membership of the @altoros GitHub org will help our bot
with its confusion Gaston :)

Thanks for the PR! The Pivotal community pair will take a closer look at
this soon.

On Friday, October 25, 2013, Gastón Ramos wrote:

> Hi, I work for Altoros. The company has already signed the agreement. In
> fact, during February and March I was pairing at Pivotal offices
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/cloudfoundry/bosh-sample-release/pull/8#issuecomment-27111406
> .

## 

tiny keyboard + fat fingers

**Comment by gramos** [comment]
ok, thanks!

**Comment by nwade** [comment]
Merged https://github.com/cloudfoundry/bosh-sample-release/commit/f92448fd99060743989e8ded9edf34c238e8eda6

**Pull request merged**
