### PR TITLE
Missing properties in wordpress-openstack.yml

### PR DESCRIPTION
**Pull request by 0xd3adcafe**
```
root@inception:/var/vcap/releases/bosh-sample-release# bosh deploy
Current deployment is /var/vcap/releases/bosh-sample-release/wordpress-openstack.yml
Getting deployment properties from director...
Compiling deployment manifest...
Please review all changes carefully
Deploying `wordpress-openstack.yml' to `microbosh-openstack' (type 'yes' to continue): yes

Director task 4

Preparing deployment
  binding deployment (00:00:00)                                                                     
  binding releases (00:00:00)                                                                       
  binding existing deployment (00:00:00)                                                            
  binding resource pools (00:00:00)                                                                 
  binding stemcells (00:00:00)                                                                      
  binding templates (00:00:00)                                                                      
  binding properties (00:00:00)                                                                     
  binding unallocated VMs (00:00:00)                                                                
  binding instance networks (00:00:00)                                                              
Done                    9/9 00:00:00                                                                

Preparing package compilation
  finding packages to compile (00:00:00)                                                            
Done                    1/1 00:00:00                                                                

Preparing DNS
  binding DNS (00:00:01)                                                                            
Done                    1/1 00:00:01                                                                

Creating bound missing VMs
  common/0 (00:02:39)                                      
  common/3 (00:02:57)                                                                               
  common/2 (00:03:02)                                                                               
  common/1 (00:03:13)                                                                               
Done                    4/4 00:03:13                                                                

Binding instance VMs
  nfs/0 (00:00:01)                                                                                  
  wordpress/0 (00:00:01)                                                                            
  nginx/0 (00:00:01)                                                                                
  mysql/0 (00:00:01)                                                                                
Done                    4/4 00:00:01                                                                

Preparing configuration
  binding configuration: Error filling in template `nginx.conf.erb' for `nginx/0' (line 2: undefined method `workers' for nil:NilClass) (00:00:00)
Error                   1/1 00:00:00                                                                

Error 80006: Error filling in template `nginx.conf.erb' for `nginx/0' (line 2: undefined method `workers' for nil:NilClass)

Task 4 error
```

### CODE REVIEW

**Comment by frodenas** [comment]
What director/stemcell version are you using? Numbers of workers are defined [here](https://github.com/cloudfoundry/bosh-sample-release/blob/master/jobs/nginx/spec#L13), so director will pick up the default value if it not set at the deployment manifest.

**Comment by 0xd3adcafe** [comment]
```
root@inception:/var/vcap/deployments# bosh status
Updating director data... done

Director
  Name      microbosh-openstack
  URL       http://10.10.4.100:25555
  Version   0.7 (release:121e9471 bosh:a2e9ab8a)
  User      admin
  UUID      b2d98c65-efe9-4dfe-8e2e-5f705846ae28
  CPI       openstack
  dns       enabled

Deployment
  Manifest  /var/vcap/releases/bosh-sample-release/wordpress-openstack.yml
root@inception:~# bosh stemcells

+---------------+---------+--------------------------------------+
| Name          | Version | CID                                  |
+---------------+---------+--------------------------------------+
| bosh-stemcell | 0.7.0   | 7a1d2b20-d8c2-41de-99f9-6b0770e583ef |
+---------------+---------+--------------------------------------+

Stemcells total: 1

root@inception:/var/vcap/releases/bosh-release# gem list bosh

*** LOCAL GEMS ***

bosh_aws_cpi (0.7.0)
bosh_aws_registry (0.2.3)
bosh_cli (1.0.3)
bosh_common (0.5.5, 0.5.3)
bosh_cpi (0.5.1)
bosh_deployer (1.4.1)
bosh_encryption (0.0.3)
bosh_openstack_cpi (0.0.7)
bosh_openstack_registry (0.0.5)
bosh_vcloud_cpi (0.4.9)
bosh_vsphere_cpi (0.6.0)
```

**Comment by 0xd3adcafe** [comment]
wordpress-openstack.yml.

```
root@inception:/var/vcap/releases/bosh-sample-release# cat wordpress-openstack.yml
---
name: wordpress
director_uuid: b2d98c65-efe9-4dfe-8e2e-5f705846ae28

release:
  name: wordpress
  version: latest

compilation:
  workers: 3
  network: default
  reuse_compilation_vms: true
  cloud_properties:
    instance_type: m0.small

update:
  canaries: 1
  canary_watch_time: 3000-120000
  update_watch_time: 3000-120000
  max_in_flight: 4
  max_errors: 1

networks:
  - name: floating
    type: vip
    cloud_properties: {}
  - name: default
    type: dynamic
    cloud_properties:
      security_groups:
      - freedom # CHANGE: Security Group

resource_pools:
  - name: common
    network: default
    size: 4
    stemcell:
      name: bosh-stemcell
      version: latest
    cloud_properties:
      instance_type: m0.small

jobs:
  - name: mysql
    template: mysql
    instances: 1
    resource_pool: common
    networks:
      - name: default
        default: [dns, gateway]

  - name: nfs
    template: debian_nfs_server
    instances: 1
    resource_pool: common
    networks:
      - name: default
        default: [dns, gateway]

  - name: wordpress
    template: wordpress
    instances: 1
    resource_pool: common
    networks:
      - name: default
        default: [dns, gateway]

  - name: nginx
    template: nginx
    instances: 1
    resource_pool: common
    networks:
      - name: default
        default: [dns, gateway]
      - name: floating
        static_ips:
        - 10.10.4.200 # CHANGE: Floating IP 1

properties:
  env:

  mysql:
    address: 0.mysql.default.wordpress.microbosh
    password: rootpass

  nfs_server:
    address: 0.nfs.default.wordpress.microbosh
    network: *.wordpress.microbosh
    idmapd_domain: novalocal

  wordpress:
    admin: foo@bar.com
    servers:
      - 0.wordpress.default.wordpress.microbosh
    servername: 10.10.4.200
    db:
      name: wp
      user: wordpress
      pass: w0rdpr3ss
    auth_key: random key
    secure_auth_key: random key
    logged_in_key: random key
    nonce_key: random key
    auth_salt: random key
    secure_auth_salt: random key
    logged_in_salt: random key
    nonce_salt: random key
  nginx:
    workers: 1
```

**Comment by frodenas** [comment]
Did you build the stemcell or used a public one? Can you please try the latest one: `bosh download public stemcell micro-bosh-stemcell-openstack-kvm-0.8.1.tgz`

**Comment by 0xd3adcafe** [comment]
I build the microbosh reference this document: https://github.com/drnic/bosh-getting-started/blob/master/create-a-bosh/creating-a-micro-bosh-from-stemcell-openstack.md, will try with the public one instead. 
Thanks.

**Comment by frodenas** [comment]
That document uses a repo that has not been updated. I'll modify the doc during this week.

**Comment by 0xd3adcafe** [comment]
I test with the `micro-bosh-stemcell-openstack-kvm-0.8.1.tgz` , but got the same error .. any idea ?

```
root@inception:/tmp# bosh status
Updating director data... done

Director
  Name      microbosh-openstack
  URL       http://10.10.4.100:25555
  Version   0.7 (release:b240cdfb bosh:57b31b3f)
  User      admin
  UUID      f96210f2-7cf1-4fba-96db-f59d3abff121
  CPI       openstack
  dns       enabled

Deployment
  Manifest  /var/vcap/releases/bosh-sample-release/wordpress-openstack.yml

```

**Comment by frodenas** [comment]
I'm testing it right now.

**Comment by 0xd3adcafe** [comment]
It's work now, Thank you.

**Pull request closed without merging**
